package lellson.wizardingtools.items;

import lellson.wizardingtools.WizardingTools;
import lellson.wizardingtools.items.baubles.ItemAmuletOfLevitation;
import lellson.wizardingtools.items.baubles.ItemAmuletOfReborn;
import lellson.wizardingtools.items.baubles.ItemBeltOfEnder;
import lellson.wizardingtools.items.baubles.ItemBeltOfMetalSkin;
import lellson.wizardingtools.items.baubles.ItemBeltOfTheSteelFeet;
import lellson.wizardingtools.items.baubles.ItemBeltOfTheSteelwing;
import lellson.wizardingtools.items.baubles.ItemBeltOfTheWind;
import lellson.wizardingtools.items.baubles.ItemBeltOfWrath;
import lellson.wizardingtools.items.baubles.ItemEnhancedLifeforcePendant;
import lellson.wizardingtools.items.baubles.ItemLifeforcePendant;
import lellson.wizardingtools.items.baubles.ItemOPRing;
import lellson.wizardingtools.items.baubles.ItemRingOfAntiBlindness;
import lellson.wizardingtools.items.baubles.ItemRingOfAntiFreeze;
import lellson.wizardingtools.items.baubles.ItemRingOfAntiVenom;
import lellson.wizardingtools.items.baubles.ItemRingOfAntiWeakness;
import lellson.wizardingtools.items.baubles.ItemRingOfAntiWither;
import lellson.wizardingtools.items.baubles.ItemRingOfCaving;
import lellson.wizardingtools.items.baubles.ItemRingOfDarkVision;
import lellson.wizardingtools.items.baubles.ItemRingOfDigging;
import lellson.wizardingtools.items.baubles.ItemRingOfHeatResistance;
import lellson.wizardingtools.items.baubles.ItemRingOfPotionProtection;
import lellson.wizardingtools.items.baubles.ItemRingOfRegeneration;
import lellson.wizardingtools.items.baubles.ItemRingOfTheElements;
import lellson.wizardingtools.items.baubles.ItemRingOfWaterBreathing;
import lellson.wizardingtools.items.baubles.ItemRingofAntiHunger;
import lellson.wizardingtools.items.baubles.ItemTitanAmulet;
import lellson.wizardingtools.items.baubles.ItemTitanBelt;
import lellson.wizardingtools.items.baubles.ItemTitanRing;
import lellson.wizardingtools.items.misc.ItemCrushingBlade;
import lellson.wizardingtools.items.misc.ItemLaserProjectile;
import lellson.wizardingtools.items.misc.ItemRailProjectile;
import lellson.wizardingtools.items.misc.ItemTitanString;
import lellson.wizardingtools.items.misc.ItemTitaniumRod;
import lellson.wizardingtools.items.resources.ItemAmethyst;
import lellson.wizardingtools.items.resources.ItemAmethystDust;
import lellson.wizardingtools.items.resources.ItemBlueTitanAlloy;
import lellson.wizardingtools.items.resources.ItemBlueTitanMixture;
import lellson.wizardingtools.items.resources.ItemCrystalDust;
import lellson.wizardingtools.items.resources.ItemEnhancedTitanDust;
import lellson.wizardingtools.items.resources.ItemEnhancedTitanIngot;
import lellson.wizardingtools.items.resources.ItemEnhancedTitaniumNugget;
import lellson.wizardingtools.items.resources.ItemGreenTitanAlloy;
import lellson.wizardingtools.items.resources.ItemGreenTitanMixture;
import lellson.wizardingtools.items.resources.ItemMalachite;
import lellson.wizardingtools.items.resources.ItemMalachiteDust;
import lellson.wizardingtools.items.resources.ItemOpal;
import lellson.wizardingtools.items.resources.ItemOpalDust;
import lellson.wizardingtools.items.resources.ItemOrangeTitanAlloy;
import lellson.wizardingtools.items.resources.ItemOrangeTitanMixture;
import lellson.wizardingtools.items.resources.ItemPurpleTitanAlloy;
import lellson.wizardingtools.items.resources.ItemPurpleTitanMixture;
import lellson.wizardingtools.items.resources.ItemRedTitanAlloy;
import lellson.wizardingtools.items.resources.ItemRedTitanMixture;
import lellson.wizardingtools.items.resources.ItemRuby;
import lellson.wizardingtools.items.resources.ItemRubyDust;
import lellson.wizardingtools.items.resources.ItemSapphire;
import lellson.wizardingtools.items.resources.ItemSapphireDust;
import lellson.wizardingtools.items.resources.ItemTitaniumDust;
import lellson.wizardingtools.items.resources.ItemTitaniumIngot;
import lellson.wizardingtools.items.resources.ItemTitaniumNugget;
import lellson.wizardingtools.items.resources.ItemTopaz;
import lellson.wizardingtools.items.resources.ItemTopazDust;
import lellson.wizardingtools.items.resources.ItemYellowTitanAlloy;
import lellson.wizardingtools.items.resources.ItemYellowTitanMixture;
import lellson.wizardingtools.items.tools.ItemEnhancedTitanAxe;
import lellson.wizardingtools.items.tools.ItemEnhancedTitanHoe;
import lellson.wizardingtools.items.tools.ItemEnhancedTitanPickaxe;
import lellson.wizardingtools.items.tools.ItemEnhancedTitanShovel;
import lellson.wizardingtools.items.tools.ItemEnhancedTitanSword;
import lellson.wizardingtools.items.tools.ItemEnhancedTitaniumBoots;
import lellson.wizardingtools.items.tools.ItemEnhancedTitaniumChestplate;
import lellson.wizardingtools.items.tools.ItemEnhancedTitaniumHelmet;
import lellson.wizardingtools.items.tools.ItemEnhancedTitaniumLeggings;
import lellson.wizardingtools.items.tools.ItemLaserGun;
import lellson.wizardingtools.items.tools.ItemLightSaberB;
import lellson.wizardingtools.items.tools.ItemLightSaberG;
import lellson.wizardingtools.items.tools.ItemLightSaberO;
import lellson.wizardingtools.items.tools.ItemLightSaberP;
import lellson.wizardingtools.items.tools.ItemLightSaberR;
import lellson.wizardingtools.items.tools.ItemLightSaberY;
import lellson.wizardingtools.items.tools.ItemRailGun;
import lellson.wizardingtools.items.tools.ItemTitanAxe;
import lellson.wizardingtools.items.tools.ItemTitanBow;
import lellson.wizardingtools.items.tools.ItemTitanHoe;
import lellson.wizardingtools.items.tools.ItemTitanPickaxe;
import lellson.wizardingtools.items.tools.ItemTitanShovel;
import lellson.wizardingtools.items.tools.ItemTitanSword;
import lellson.wizardingtools.items.tools.ItemTitaniumArmor;
import lellson.wizardingtools.items.wands.ItemWandOfNature;
import lellson.wizardingtools.util.WizardingConfig;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.registry.GameRegistry;

public final class WizardingItems {
	
	public static Item itemTitaniumIngot;
	public static Item itemRuby;
	public static Item itemSapphire;
	public static Item itemAmethyst;
	public static Item itemTopaz;
	public static Item itemOpal;
	public static Item itemMalachite;
	public static Item itemTitanSword;
	public static Item itemTitanPickaxe;
	public static Item itemTitanAxe;
	public static Item itemTitanShovel;
	public static Item itemTitanHoe;
	public static Item itemEnhancedTitanSword;
	public static Item itemEnhancedTitanPickaxe;
	public static Item itemEnhancedTitanAxe;
	public static Item itemEnhancedTitanShovel;
	public static Item itemEnhancedTitanHoe;
	public static Item itemTitaniumDust;
	public static Item itemEnhancedTitanIngot;
	public static Item itemEnhancedTitanDust;
	public static Item itemCrystalDust;
	public static Item itemRubyDust;
	public static Item itemSapphireDust;
	public static Item itemAmethystDust;
	public static Item itemTopazDust;
	public static Item itemOpalDust;
	public static Item itemMalachiteDust;
	public static Item itemRedTitanAlloy;
	public static Item itemBlueTitanAlloy;
	public static Item itemYellowTitanAlloy;
	public static Item itemPurpleTitanAlloy;
	public static Item itemOrangeTitanAlloy;
	public static Item itemGreenTitanAlloy;
	public static Item itemRedTitanMixture;
	public static Item itemBlueTitanMixture;
	public static Item itemYellowTitanMixture;
	public static Item itemPurpleTitanMixture;
	public static Item itemOrangeTitanMixture;
	public static Item itemGreenTitanMixture;
	public static Item itemTitaniumRod;
	public static Item itemTitaniumHelmet;
	public static Item itemTitaniumChestplate;
	public static Item itemTitaniumLeggings;
	public static Item itemTitaniumBoots;
	public static Item itemEnhancedTitaniumHelmet;
	public static Item itemEnhancedTitaniumChestplate;
	public static Item itemEnhancedTitaniumLeggings;
	public static Item itemEnhancedTitaniumBoots;
	public static Item itemTitanString;
	public static Item itemTitaniumNugget;
	public static Item itemEnhancedTitaniumNugget;
	public static Item itemCrushingBlade;
	public static Item itemTitanRing;
	public static Item itemTitanAmulet;
	public static Item itemTitanBelt;
	public static Item itemRingOfAntiVenom;
	public static Item itemRingOfAntiWither;
	public static Item itemRingOfAntiFreeze;
	public static Item itemRingofAntiHunger;
	public static Item itemRingOfAntiWeakness;
	public static Item itemRingOfAntiBlindness;
	public static Item itemRingOfPotionProtection;
	public static Item itemBeltOfTheWind;
	public static Item itemBeltOfTheSteelFeet;
	public static Item itemBeltOfTheSteelwing;
	public static Item itemLifeforcePendant;
	public static Item itemEnhancedLifeforcePendant;
	public static Item itemRingOfHeatResistance;
	public static Item itemRingOfWaterBreathing;
	public static Item itemRingOfTheElements;
	public static Item itemBeltOfWrath;
	public static Item itemBeltOfMetalSkin;
	public static Item itemRingOfDarkVision;
	public static Item itemRingOfDigging;
	public static Item itemRingOfCaving;
	public static Item itemAmuletOfLevitation;
	public static Item itemAmuletOfReborn;
	public static Item itemRingOfRegeneration;
	public static Item itemLightSaberR;
	public static Item itemLightSaberB;
	public static Item itemLightSaberY;
	public static Item itemLightSaberP;
	public static Item itemLightSaberO;
	public static Item itemLightSaberG;
	public static Item itemLaserGun;
	public static Item itemLaserProjectile;
	public static Item itemRailGun;
	public static Item itemRailProjectile;
	public static Item itemBeltOfEnder;
	public static Item itemWandOfNature;
	public static Item itemOPRing;
	public static Item itemTitanBow;

	public static ToolMaterial materialTitanium = EnumHelper.addToolMaterial("materialTitanium", 3, 650, 10.0F, 4.0F, 15);
	public static ToolMaterial materialEnhancedTitanium = EnumHelper.addToolMaterial("materialEnhancedTitanium", 4, 32000, 14.0F, 6.0F, 18);
	public static ToolMaterial materialLightSaber = EnumHelper.addToolMaterial("materialLightSaber", 3, 32000, 10.0F, 4.0F, 25);
	
	public static ArmorMaterial materialTitaniumA = EnumHelper.addArmorMaterial("materialTitaniumA", 21, new int[]{3, 8, 6, 3}, 12);
	public static ArmorMaterial materialEnhancedTitaniumA = EnumHelper.addArmorMaterial("materialEnhancedTitaniumA", 100, new int[]{4, 9, 7, 4}, 15);
	private static boolean modinstalled = false;
	
	public static final void init() {
		
		itemTitaniumIngot = new ItemTitaniumIngot().setUnlocalizedName("ItemTitaniumIngot").setTextureName("wt:itemtitaniumingot").setCreativeTab(WizardingTools.tabWizardingTools);
		
	if (modinstalled  = Loader.isModLoaded("BiomesOPlenty") || Loader.isModLoaded("gregtech") || Loader.isModLoaded("ProjRed|Exploration")) {
		itemRuby = new ItemRuby().setUnlocalizedName("ItemRubyBoP").setTextureName("wt:itemruby").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRubyDust = new ItemRubyDust().setUnlocalizedName("ItemRubyDustBoP").setTextureName("wt:itemrubydust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemSapphire = new ItemSapphire().setUnlocalizedName("ItemSapphireBoP").setTextureName("wt:itemsapphire").setCreativeTab(WizardingTools.tabWizardingTools);
		itemSapphireDust = new ItemSapphireDust().setUnlocalizedName("ItemSapphireDustBoP").setTextureName("wt:itemsapphiredust").setCreativeTab(WizardingTools.tabWizardingTools);
	} else {
		itemRuby = new ItemRuby().setUnlocalizedName("ItemRuby").setTextureName("wt:itemruby").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRubyDust = new ItemRubyDust().setUnlocalizedName("ItemRubyDust").setTextureName("wt:itemrubydust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemSapphire = new ItemSapphire().setUnlocalizedName("ItemSapphire").setTextureName("wt:itemsapphire").setCreativeTab(WizardingTools.tabWizardingTools);
		itemSapphireDust = new ItemSapphireDust().setUnlocalizedName("ItemSapphireDust").setTextureName("wt:itemsapphiredust").setCreativeTab(WizardingTools.tabWizardingTools);
	}
	if (modinstalled  = Loader.isModLoaded("BiomesOPlenty")) {
		itemAmethyst = new ItemAmethyst().setUnlocalizedName("ItemAmethystBoP").setTextureName("wt:itemamethyst").setCreativeTab(WizardingTools.tabWizardingTools);
		itemMalachite = new ItemMalachite().setUnlocalizedName("ItemMalachiteBoP").setTextureName("wt:itemmalachite").setCreativeTab(WizardingTools.tabWizardingTools);
		itemAmethystDust = new ItemAmethystDust().setUnlocalizedName("ItemAmethystDustBoP").setTextureName("wt:itemamethystdust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemMalachiteDust = new ItemMalachiteDust().setUnlocalizedName("ItemMalachiteDustBoP").setTextureName("wt:itemmalachitedust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTopaz = new ItemTopaz().setUnlocalizedName("ItemTopazBoP").setTextureName("wt:itemtopaz").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTopazDust = new ItemTopazDust().setUnlocalizedName("ItemTopazDustBoP").setTextureName("wt:itemtopazdust").setCreativeTab(WizardingTools.tabWizardingTools);
	} else {
		itemAmethyst = new ItemAmethyst().setUnlocalizedName("ItemAmethyst").setTextureName("wt:itemamethyst").setCreativeTab(WizardingTools.tabWizardingTools);
		itemMalachite = new ItemMalachite().setUnlocalizedName("ItemMalachite").setTextureName("wt:itemmalachite").setCreativeTab(WizardingTools.tabWizardingTools);
		itemAmethystDust = new ItemAmethystDust().setUnlocalizedName("ItemAmethystDust").setTextureName("wt:itemamethystdust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemMalachiteDust = new ItemMalachiteDust().setUnlocalizedName("ItemMalachiteDust").setTextureName("wt:itemmalachitedust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTopaz = new ItemTopaz().setUnlocalizedName("ItemTopaz").setTextureName("wt:itemtopaz").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTopazDust = new ItemTopazDust().setUnlocalizedName("ItemTopazDust").setTextureName("wt:itemtopazdust").setCreativeTab(WizardingTools.tabWizardingTools);
	}
	
		itemOpal = new ItemOpal().setUnlocalizedName("ItemOpal").setTextureName("wt:itemopal").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanSword = new ItemTitanSword(materialTitanium).setUnlocalizedName("ItemTitanSword").setTextureName("wt:itemtitansword").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanPickaxe = new ItemTitanPickaxe(materialTitanium).setUnlocalizedName("ItemTitanPickaxe").setTextureName("wt:itemtitanpickaxe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanAxe = new ItemTitanAxe(materialTitanium).setUnlocalizedName("ItemTitanAxe").setTextureName("wt:itemtitanaxe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanShovel = new ItemTitanShovel(materialTitanium).setUnlocalizedName("ItemTitanShovel").setTextureName("wt:itemtitanshovel").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanHoe = new ItemTitanHoe(materialTitanium).setUnlocalizedName("ItemTitanHoe").setTextureName("wt:itemtitanhoe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanSword = new ItemEnhancedTitanSword(materialEnhancedTitanium).setUnlocalizedName("ItemEnhancedTitanSword").setTextureName("wt:itemenhancedtitansword").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanPickaxe = new ItemEnhancedTitanPickaxe(materialEnhancedTitanium).setUnlocalizedName("ItemEnhancedTitanPickaxe").setTextureName("wt:itemenhancedtitanpickaxe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanAxe = new ItemEnhancedTitanAxe(materialEnhancedTitanium).setUnlocalizedName("ItemEnhancedTitanAxe").setTextureName("wt:itemenhancedtitanaxe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanShovel = new ItemEnhancedTitanShovel(materialEnhancedTitanium).setUnlocalizedName("ItemEnhancedTitanShovel").setTextureName("wt:itemenhancedtitanshovel").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanHoe = new ItemEnhancedTitanHoe(materialEnhancedTitanium).setUnlocalizedName("ItemEnhancedTitanHoe").setTextureName("wt:itemenhancedtitanhoe").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanIngot = new ItemEnhancedTitanIngot().setUnlocalizedName("ItemEnhancedTitanIngot").setTextureName("wt:itemtitaniumingot").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitanDust = new ItemEnhancedTitanDust().setUnlocalizedName("ItemEnhancedTitanDust").setTextureName("wt:itemtitaniumdust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumDust = new ItemTitaniumDust().setUnlocalizedName("ItemTitaniumDust").setTextureName("wt:itemtitaniumdust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemCrystalDust = new ItemCrystalDust().setUnlocalizedName("ItemCrystalDust").setTextureName("wt:itemcrystaldust").setCreativeTab(WizardingTools.tabWizardingTools);	
		itemOpalDust = new ItemOpalDust().setUnlocalizedName("ItemOpalDust").setTextureName("wt:itemopaldust").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRedTitanAlloy = new ItemRedTitanAlloy().setUnlocalizedName("ItemRedTitanAlloy").setTextureName("wt:itemredtitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBlueTitanAlloy = new ItemBlueTitanAlloy().setUnlocalizedName("ItemBlueTitanAlloy").setTextureName("wt:itembluetitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemYellowTitanAlloy = new ItemYellowTitanAlloy().setUnlocalizedName("ItemYellowTitanAlloy").setTextureName("wt:itemyellowtitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemPurpleTitanAlloy = new ItemPurpleTitanAlloy().setUnlocalizedName("ItemPurpleTitanAlloy").setTextureName("wt:itempurpletitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemOrangeTitanAlloy = new ItemOrangeTitanAlloy().setUnlocalizedName("ItemOrangeTitanAlloy").setTextureName("wt:itemorangetitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemGreenTitanAlloy = new ItemGreenTitanAlloy().setUnlocalizedName("ItemGreenTitanAlloy").setTextureName("wt:itemgreentitanalloy").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRedTitanMixture = new ItemRedTitanMixture().setUnlocalizedName("ItemRedTitanMixture").setTextureName("wt:itemredtitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBlueTitanMixture = new ItemBlueTitanMixture().setUnlocalizedName("ItemBlueTitanMixture").setTextureName("wt:itembluetitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemYellowTitanMixture = new ItemYellowTitanMixture().setUnlocalizedName("ItemYellowTitanMixture").setTextureName("wt:itemyellowtitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemPurpleTitanMixture = new ItemPurpleTitanMixture().setUnlocalizedName("ItemPurpleTitanMixture").setTextureName("wt:itempurpletitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemOrangeTitanMixture = new ItemOrangeTitanMixture().setUnlocalizedName("ItemOrangeTitanMixture").setTextureName("wt:itemorangetitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemGreenTitanMixture = new ItemGreenTitanMixture().setUnlocalizedName("ItemGreenTitanMixture").setTextureName("wt:itemgreentitanmixture").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumRod = new ItemTitaniumRod().setUnlocalizedName("ItemTitaniumRod").setTextureName("wt:itemtitaniumrod").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumHelmet = new ItemTitaniumArmor(materialTitaniumA, 0, 0).setUnlocalizedName("ItemTitaniumHelmet").setTextureName("wt:itemtitaniumhelmet").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumChestplate = new ItemTitaniumArmor(materialTitaniumA, 0, 1).setUnlocalizedName("ItemTitaniumChestplate").setTextureName("wt:itemtitaniumchestplate").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumLeggings = new ItemTitaniumArmor(materialTitaniumA, 0, 2).setUnlocalizedName("ItemTitaniumLeggings").setTextureName("wt:itemtitaniumleggings").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumBoots = new ItemTitaniumArmor(materialTitaniumA, 0, 3).setUnlocalizedName("ItemTitaniumBoots").setTextureName("wt:itemtitaniumboots").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitaniumHelmet = new ItemEnhancedTitaniumHelmet(materialEnhancedTitaniumA, 0, 0).setUnlocalizedName("ItemEnhancedTitaniumHelmet").setTextureName("wt:itemtitaniumhelmet").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitaniumChestplate = new ItemEnhancedTitaniumChestplate(materialEnhancedTitaniumA, 0, 1).setUnlocalizedName("ItemEnhancedTitaniumChestplate").setTextureName("wt:itemtitaniumchestplate").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitaniumLeggings = new ItemEnhancedTitaniumLeggings(materialEnhancedTitaniumA, 0, 2).setUnlocalizedName("ItemEnhancedTitaniumLeggings").setTextureName("wt:itemtitaniumleggings").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitaniumBoots = new ItemEnhancedTitaniumBoots(materialEnhancedTitaniumA, 0, 3).setUnlocalizedName("ItemEnhancedTitaniumBoots").setTextureName("wt:itemtitaniumboots").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanString = new ItemTitanString().setUnlocalizedName("ItemTitanString").setTextureName("wt:itemtitanstring").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitaniumNugget = new ItemTitaniumNugget().setUnlocalizedName("ItemTitaniumNugget").setTextureName("wt:itemtitaniumnugget").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedTitaniumNugget = new ItemEnhancedTitaniumNugget().setUnlocalizedName("ItemEnhancedTitaniumNugget").setTextureName("wt:itemtitaniumnugget").setCreativeTab(WizardingTools.tabWizardingTools);
		itemCrushingBlade = new ItemCrushingBlade().setUnlocalizedName("ItemCrushingBlade").setTextureName("wt:itemcrushingblade").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanRing = new ItemTitanRing().setUnlocalizedName("ItemTitanRing").setTextureName("wt:itemtitanring").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanAmulet = new ItemTitanAmulet().setUnlocalizedName("ItemTitanAmulet").setTextureName("wt:itemtitanamulet").setCreativeTab(WizardingTools.tabWizardingTools);
		itemTitanBelt = new ItemTitanBelt().setUnlocalizedName("ItemTitanBelt").setTextureName("wt:itemtitanbelt").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiVenom = new ItemRingOfAntiVenom().setUnlocalizedName("ItemRingOfAntiVenom").setTextureName("wt:itemringofantivenom").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiWither = new ItemRingOfAntiWither().setUnlocalizedName("ItemRingOfAntiWither").setTextureName("wt:itemringofantiwither").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiVenom = new ItemRingOfAntiVenom().setUnlocalizedName("ItemRingOfAntiVenom").setTextureName("wt:itemringofantivenom").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiFreeze = new ItemRingOfAntiFreeze().setUnlocalizedName("ItemRingOfAntiFreeze").setTextureName("wt:itemringofantifreeze").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingofAntiHunger = new ItemRingofAntiHunger().setUnlocalizedName("ItemRingofAntiHunger").setTextureName("wt:itemringofantihunger").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiWeakness = new ItemRingOfAntiWeakness().setUnlocalizedName("ItemRingOfAntiWeakness").setTextureName("wt:itemringofantiweakness").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfAntiBlindness = new ItemRingOfAntiBlindness().setUnlocalizedName("ItemRingOfAntiBlindness").setTextureName("wt:itemringofantiblindness").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfPotionProtection = new ItemRingOfPotionProtection().setUnlocalizedName("ItemRingOfPotionProtection").setTextureName("wt:itemringofpotionprotection").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfTheWind = new ItemBeltOfTheWind().setUnlocalizedName("ItemBeltOfTheWind").setTextureName("wt:itembeltofthewind").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfTheSteelFeet = new ItemBeltOfTheSteelFeet().setUnlocalizedName("ItemBeltOfTheSteelFeet").setTextureName("wt:itembeltofthesteelfeet").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfTheSteelwing = new ItemBeltOfTheSteelwing().setUnlocalizedName("ItemBeltOfTheSteelwing").setTextureName("wt:itembeltofthesteelwing").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLifeforcePendant = new ItemLifeforcePendant().setUnlocalizedName("ItemLifeforcePendant").setTextureName("wt:itemlifeforcependant").setCreativeTab(WizardingTools.tabWizardingTools);
		itemEnhancedLifeforcePendant = new ItemEnhancedLifeforcePendant().setUnlocalizedName("ItemEnhancedLifeforcePendant").setTextureName("wt:itemenhancedlifeforcependant").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfHeatResistance = new ItemRingOfHeatResistance().setUnlocalizedName("ItemRingOfHeatResistance").setTextureName("wt:itemringofheatresistance").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfWaterBreathing = new ItemRingOfWaterBreathing().setUnlocalizedName("ItemRingOfWaterBreathing").setTextureName("wt:itemringofwaterbreathing").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfTheElements = new ItemRingOfTheElements().setUnlocalizedName("ItemRingOfTheElements").setTextureName("wt:itemringoftheelements").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfWrath = new ItemBeltOfWrath().setUnlocalizedName("ItemBeltOfWrath").setTextureName("wt:itembeltofwrath").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfMetalSkin = new ItemBeltOfMetalSkin().setUnlocalizedName("ItemBeltOfMetalSkin").setTextureName("wt:itembeltofmetalskin").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfCaving = new ItemRingOfCaving().setUnlocalizedName("ItemRingOfCaving").setTextureName("wt:itemringofcaving").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfDarkVision = new ItemRingOfDarkVision().setUnlocalizedName("ItemRingOfDarkVision").setTextureName("wt:itemringofdarkvision").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfDigging = new ItemRingOfDigging().setUnlocalizedName("ItemRingOfDigging").setTextureName("wt:itemringofdigging").setCreativeTab(WizardingTools.tabWizardingTools);
		itemAmuletOfLevitation = new ItemAmuletOfLevitation().setUnlocalizedName("ItemAmuletOfLevitation").setTextureName("wt:itemamuletoflevitation").setCreativeTab(WizardingTools.tabWizardingTools);
		itemAmuletOfReborn = new ItemAmuletOfReborn().setUnlocalizedName("ItemAmuletOfReborn").setTextureName("wt:itemamuletofreborn").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRingOfRegeneration = new ItemRingOfRegeneration().setUnlocalizedName("ItemRingOfRegeneration").setTextureName("wt:itemringofregeneration").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberR = new ItemLightSaberR(materialLightSaber).setUnlocalizedName("ItemLightSaberR").setTextureName("wt:itemlightsaberr").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberB = new ItemLightSaberB(materialLightSaber).setUnlocalizedName("ItemLightSaberB").setTextureName("wt:itemlightsaberb").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberY = new ItemLightSaberY(materialLightSaber).setUnlocalizedName("ItemLightSaberY").setTextureName("wt:itemlightsabery").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberP = new ItemLightSaberP(materialLightSaber).setUnlocalizedName("ItemLightSaberP").setTextureName("wt:itemlightsaberp").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberO = new ItemLightSaberO(materialLightSaber).setUnlocalizedName("ItemLightSaberO").setTextureName("wt:itemlightsabero").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLightSaberG = new ItemLightSaberG(materialLightSaber).setUnlocalizedName("ItemLightSaberG").setTextureName("wt:itemlightsaberg").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLaserGun = new ItemLaserGun().setUnlocalizedName("ItemLaserGun").setTextureName("wt:itemlasergun").setCreativeTab(WizardingTools.tabWizardingTools);
		itemLaserProjectile = new ItemLaserProjectile().setUnlocalizedName("ItemLaserProjectile").setTextureName("wt:itemlaserprojectile");
		itemRailGun = new ItemRailGun().setUnlocalizedName("ItemRailGun").setTextureName("wt:itemrailgun").setCreativeTab(WizardingTools.tabWizardingTools);
		itemRailProjectile = new ItemRailProjectile().setUnlocalizedName("ItemRailProjectile").setTextureName("wt:itemrailprojectile").setCreativeTab(WizardingTools.tabWizardingTools);
		itemBeltOfEnder = new ItemBeltOfEnder().setUnlocalizedName("ItemBeltOfEnder").setTextureName("wt:itembeltofender").setCreativeTab(WizardingTools.tabWizardingTools);
		itemOPRing = new ItemOPRing().setUnlocalizedName("ItemOPRing").setTextureName("wt:itemopring").setCreativeTab(WizardingTools.tabWizardingTools);
		//itemWandOfNature = new ItemWandOfNature().setUnlocalizedName("ItemWandOfNature").setTextureName("wt:itemwandofnature").setCreativeTab(WizardingTools.tabWizardingTools);
		//itemTitanBow = new ItemTitanBow().setUnlocalizedName("ItemTitanBow").setTextureName("wt:itemtitanbow").setCreativeTab(WizardingTools.tabWizardingTools);
		
		GameRegistry.registerItem(itemTitaniumIngot, itemTitaniumIngot.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRuby, itemRuby.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemSapphire, itemSapphire.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemAmethyst, itemAmethyst.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTopaz, itemTopaz.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOpal, itemOpal.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemMalachite, itemMalachite.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanSword, itemTitanSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanPickaxe, itemTitanPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanAxe, itemTitanAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanShovel, itemTitanShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanHoe, itemTitanHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanSword, itemEnhancedTitanSword.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanPickaxe, itemEnhancedTitanPickaxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanAxe, itemEnhancedTitanAxe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanShovel, itemEnhancedTitanShovel.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanHoe, itemEnhancedTitanHoe.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanIngot, itemEnhancedTitanIngot.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitanDust, itemEnhancedTitanDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumDust, itemTitaniumDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemCrystalDust, itemCrystalDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRubyDust, itemRubyDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemSapphireDust, itemSapphireDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTopazDust, itemTopazDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemAmethystDust, itemAmethystDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOpalDust, itemOpalDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemMalachiteDust, itemMalachiteDust.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRedTitanAlloy, itemRedTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBlueTitanAlloy, itemBlueTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemYellowTitanAlloy, itemYellowTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemPurpleTitanAlloy, itemPurpleTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOrangeTitanAlloy, itemOrangeTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemGreenTitanAlloy, itemGreenTitanAlloy.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRedTitanMixture, itemRedTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBlueTitanMixture, itemBlueTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemYellowTitanMixture, itemYellowTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemPurpleTitanMixture, itemPurpleTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOrangeTitanMixture, itemOrangeTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemGreenTitanMixture, itemGreenTitanMixture.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumRod, itemTitaniumRod.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumHelmet, itemTitaniumHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumChestplate, itemTitaniumChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumLeggings, itemTitaniumLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumBoots, itemTitaniumBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitaniumHelmet, itemEnhancedTitaniumHelmet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitaniumChestplate, itemEnhancedTitaniumChestplate.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitaniumLeggings, itemEnhancedTitaniumLeggings.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitaniumBoots, itemEnhancedTitaniumBoots.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanString, itemTitanString.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitaniumNugget, itemTitaniumNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedTitaniumNugget, itemEnhancedTitaniumNugget.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemCrushingBlade, itemCrushingBlade.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanRing, itemTitanRing.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanAmulet, itemTitanAmulet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemTitanBelt, itemTitanBelt.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfAntiVenom, itemRingOfAntiVenom.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfAntiWither, itemRingOfAntiWither.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfAntiFreeze, itemRingOfAntiFreeze.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingofAntiHunger, itemRingofAntiHunger.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfAntiWeakness, itemRingOfAntiWeakness.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfAntiBlindness, itemRingOfAntiBlindness.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfPotionProtection, itemRingOfPotionProtection.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfTheWind, itemBeltOfTheWind.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfTheSteelFeet, itemBeltOfTheSteelFeet.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfTheSteelwing, itemBeltOfTheSteelwing.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLifeforcePendant, itemLifeforcePendant.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemEnhancedLifeforcePendant, itemEnhancedLifeforcePendant.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfHeatResistance, itemRingOfHeatResistance.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfWaterBreathing, itemRingOfWaterBreathing.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfTheElements, itemRingOfTheElements.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfWrath, itemBeltOfWrath.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfMetalSkin, itemBeltOfMetalSkin.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfCaving, itemRingOfCaving.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfDarkVision, itemRingOfDarkVision.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfDigging, itemRingOfDigging.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemAmuletOfLevitation, itemAmuletOfLevitation.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemAmuletOfReborn, itemAmuletOfReborn.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRingOfRegeneration, itemRingOfRegeneration.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberR, itemLightSaberR.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberB, itemLightSaberB.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberY, itemLightSaberY.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberP, itemLightSaberP.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberO, itemLightSaberO.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLightSaberG, itemLightSaberG.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLaserGun, itemLaserGun.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemLaserProjectile, itemLaserProjectile.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRailGun, itemRailGun.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemRailProjectile, itemRailProjectile.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemBeltOfEnder, itemBeltOfEnder.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemOPRing, itemOPRing.getUnlocalizedName().substring(5));
		//GameRegistry.registerItem(itemWandOfNature, itemWandOfNature.getUnlocalizedName().substring(5));
		//GameRegistry.registerItem(itemTitanBow, itemTitanBow.getUnlocalizedName().substring(5));
	}

}
